### ISSUE TITLE
Mybinder dont work :(

### ISSUE THREAD

**Issue by borisalmonacid** [riveSunder/yuca#26]
from: https://mybinder.org/v2/gh/riveSunder/yuca/gecco_2022_pages?urlpath=/proxy/5006/gecco_bokeh_app

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/28852633/189747377-bcf4e84c-ceee-4a9d-8353-06f7d0256c95.png">

**Comment by riveSunder** [comment]
Thanks for pointing this out, we seem to have lost some functionality of mybinder serving bokeh apps (I've seen this in another project as well). I will provide an alternative and post here when it's done.

**Comment by riveSunder** [comment]
Mybinder is apparently working again, but slow. I will close this issue for now, but I will open another issue for adding a more responsive alternative. 
![image](https://github.com/riveSunder/yuca/assets/38316715/dbd16b68-bef5-4817-a457-7678fe7c4efc)
